version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_DATABASE: 'cours'
    ports:
      - 3306:3306
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: ./.docker/php/
    volumes:
      - .:/var/www
    links:
      - mysql